version: '3.8'

services:
  vidalia:
    container_name: vidalia
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=src/app.py
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
