name: Python Test and Coverage

# We enforce 100% code coverage using Docker with Python 3.13

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shallot-backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Run tests inside a Python 3.13 Docker container
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Test Shallot Backend with Python 3.13
      uses: docker/build-push-action@v6
      with:
        context: ./shallot/backend
        file: ./shallot/backend/Dockerfile.test
        push: false
        tags: shallot-backend-test:latest
        target: test
        outputs: type=local,dest=./shallot/backend/coverage
        build-args: |
          PYTHON_VERSION=3.13
          COVERAGE_THRESHOLD=100
    
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: shallot-coverage
        path: ./shallot/backend/coverage/htmlcov/
        if-no-files-found: error

  vidalia-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      working-directory: ./vidalia
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests with coverage
      working-directory: ./vidalia
      run: |
        mkdir -p coverage/htmlcov
        python -m pytest -v --cov=src --cov-report=html:coverage/htmlcov --cov-report=term --cov-config=.coveragerc
    
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vidalia-coverage
        path: ./vidalia/coverage/htmlcov/
        if-no-files-found: error